# Generated by Django 5.1.3 on 2024-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_person_gender_alter_person_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profie_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
